Atlas-OS/docs

mkdocs.yml
By request, change the FAQ link to go to atlasos.net/faq. Using this PR to test if this method works.
=> feat: 📝 use atlasos.net/faq for FAQ

mkdocs.yml
=> Faq remake

docs/getting-started/installation.md
- [ no ] Rewrite already written documentation.
- [ no ] Add/remove new pages.
- [ no ] Did you preview on your local machine beforehand?
- [ no ] Did you follow our [commit handbook](https://github.com/Atlas-OS/Atlas/pull/713)?
=> Fixed typo in installation.md

docs/getting-started/post-installation/configuration/index.md
I edited 2 links in the index.md under `docs/getting-started/post-installation/configuration/` , because it gives an 404 error.
https://user-images.githubusercontent.com/92390724/235318782-06ec00ca-4aa9-4421-9218-1acf5bd70276.mp4
=> fix: 404 error

docs/getting-started/installation.md
Currently, there are 2 `Post-instalation`, [this one](https://docs.atlasos.net/getting-started/installation/#post-installation) and [this one](https://docs.atlasos.net/getting-started/post-installation).
This is just a minor change to fix that because it may confuse someone.
=> refactor: 📝 installation

docs/getting-started/post-installation/configuration/index.md
Populated documentation for CPU Idle section.
=> Write documentation for CPU idle states

.github/CONTRIBUTING.md, README.md, docs/getting-started/installation.md, docs/getting-started/other-installation-methods/no-usb.md, docs/getting-started/post-installation/configuration/advanced-configuration.md, docs/getting-started/post-installation/configuration/index.md, docs/getting-started/post-installation/configuration/optional-tweaks.md, docs/getting-started/post-installation/configuration/windows-settings.md, docs/getting-started/post-installation/drivers/gpu/amd.md, docs/getting-started/post-installation/drivers/gpu/intel.md, docs/getting-started/post-installation/drivers/gpu/nvidia.md, docs/getting-started/post-installation/drivers/index.md, docs/getting-started/post-installation/index.md, docs/getting-started/post-installation/software/index.md, docs/index.md, docs/troubleshooting/common-issues/adobe/acrobat-fails-to-install.md, docs/troubleshooting/common-issues/adobe/creative-cloud-error-191.md, docs/troubleshooting/common-issues/atlas-folder-missing.md, docs/troubleshooting/common-issues/csgo-vac-no-session-verified.md, docs/troubleshooting/common-issues/hyper-v.md, docs/troubleshooting/common-issues/mobile-hotspot.md, docs/troubleshooting/common-issues/process-hacker.md, docs/troubleshooting/common-issues/reticulating-splines.md, docs/troubleshooting/removed-features.md, docs/troubleshooting/scripts.md, mkdocs.insiders.yml, mkdocs.yml, overrides/partials/integrations/analytics/custom.html, requirements.txt
* Corrects tiny mistakes and improves clarity
* Implements Microsoft Clarity for UX reports
* ~~Uses ``timeago`` rather than ``datetime`` for git-revision-date-localized~~
* See below.
* ~~Disables creation date lookup (fetch depth can't be set @ Cloudflare Pages)~~
* Disables git-revision-date-localized completely as the fetch depth is too low during build at Cloudflare Pages, making the creation and last updated date both show the build date and time at Cloudflare Pages.
* Added descriptions and icons to each page
* Removed unneeded index pages
* Updated font for metadata image generation
=> Analytics and SEO update

docs/getting-started/other-installation-methods/no-usb.md
Fixed the "Post installation" link from https://docs.atlasos.net/getting-started/post-installation/ which leads to Error 404 to https://docs.atlasos.net/getting-started/post-installation/drivers/ which now leads to the driver section.
=> Fixed the "Post Installtion" link (no-usb.md)

docs/getting-started/installation.md
=> fix a link in installation.md

mkdocs.insiders.yml, mkdocs.yml, requirements.txt
* Restructure of configs
* Now use ``mkdocs.yml`` for all configuration, while ``mkdocs.insiders.yml`` only contains configurations for **Insider plugins**.
* Fix for social cards
=> fix(social): work on social cards

docs/getting-started/post-installation/configuration/windows-settings.md, docs/troubleshooting/common-issues/atlas-folder-missing.md
Fixes broken links in docs. I had already created pr's for these, but the links became invalid again when the directory names changed again.
=> Fix invalid links

docs/getting-started/installation.md
Discussed internally. The video in installation page is way too outdated and people were confused by it. It can be added back whenever there is a up to date one.
=> docs: remove outdated video from installation

docs/getting-started/post-installation/configuration/index.md, docs/getting-started/post-installation/configuration/optional-tweaks.md, docs/getting-started/post-installation/security/index.md
This is a start to make sure the sections reflect the content shown in the RC2. Not all information is filled, but I have deleted obsolete sections and created new sections for new content.
=> Rework Post-Install section to reflect RC2

docs/getting-started/post-installation/atlas-folder/advanced-configuration.md
Contributing Documentation for Advanced Configuration Section (this has been needed for a while)
=> feat: Advanced Configuration

docs/getting-started/post-installation/drivers/gpu/nvidia.md
=> Fix bad link

docs/faq-and-troubleshooting/common-questions/itunes-compatibility.md
=> fix duck sleep on jack keyboard

docs/branding.md, docs/contributions.md, docs/faq-and-troubleshooting/common-questions/atlas-iso-files.md, docs/faq-and-troubleshooting/common-questions/bluetooth-compatibility.md, docs/faq-and-troubleshooting/common-questions/decryptying-using-bitlocker.md, docs/faq-and-troubleshooting/common-questions/itunes-compatibility.md, docs/faq-and-troubleshooting/common-questions/microsoft-store-compatibility.md, docs/faq-and-troubleshooting/removed-features.md, docs/getting-started/installation.md, docs/index.md
=> fix: typo, language, and more

docs/javascript/msdl.js
=> Merge dev -> master

docs/getting-started/post-installation/software/text-editors.md
=> Fixed typo (y -> t)

overrides/main.html
=> The wording was changed to be closer to the original

docs/faq-and-troubleshooting/common-questions/recommended-antiviruses.md, mkdocs.yml
- [y] Add/remove new pages.
- [y] Did you preview on your local machine beforehand?
- [y] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [y] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [y] Did you commit to the `dev` branch and not `master`?
Added recommended antiviruses
=> docs(faq): add recommended antiviruses

docs/faq-and-troubleshooting/common-questions/home-vs-pro.md
=> docs(faq): add home vs pro

docs/faq-and-troubleshooting/common-questions/windows-editions.md
Fixed a really small typo on the new Windows Editions page.
=> fix: small typo in windows-editions.md

docs/getting-started/post-installation/drivers/intel.md
Put Intel page first since OEM drivers usually only get backported critical fixes.
=> Rewrite Intel driver page

docs/getting-started/installation.md
No one say "Networking driver" lol.
I corrected its technical aspect and made it easier to understand by changing the format + provide an example how user should search for the driver + what users should do when they have 2 network interfaces.
=> Rewrite "Networking Driver"

docs/faq-and-troubleshooting/common-questions/recommended-antiviruses.md
Kaspersky realtime free no longer exists, removed it from AV listing.
=> fix: kaspersky realtime free no longer exists

docs/faq-and-troubleshooting/common-questions/recommended-antiviruses.md
Of course github's editor didn't show the right indents.
=> fix: indentation pt. 2 on recommended-antiviruses

docs/getting-started/installation.md
=> feat: Update MSDL Credit

overrides/404.html
Added a better 404 page with contact/PR links and useful buttons.
Appearance:
Go back button is `javascript:history.back()` (same as hitting your browser's back button)
Home button is `/`
Contact link is `discord.atlasos.net`
=> Better 404 page

docs/faq-and-troubleshooting/common-questions/roblox-not-opening.md
A single change to make setting paths more precise on the "Roblox not opening" page.
=> More precise setting paths on the "Roblox not opening" page

docs/getting-started/post-installation/drivers/nvidia.md
changes to the existing nvidia guide
=> docs: refactor nvidia.md

docs/faq-and-troubleshooting/common-questions/roblox-not-opening.md
Adds windows version icons to #199
=> (fix): Add Windows version icons to roblox page

docs/getting-started/installation.md
- Added warning for bypassing requirements.
- Moved the Windows 11 recommendation to the ISO download.
- More clarification on which Windows version is best for the user, this is one of the most asked questions in the support channels.
=> docs: minor improvements installation.md

docs/getting-started/post-installation/drivers/nvidia.md
Fixed punctuation and the admonition title not displaying properly.
=> docs: fix admonition title and punctuation nvidia.md

docs/contributions.md
Over time, I've noticed that almost none of the automatic pull requests get merged and that they often need to be reviewed when they do. Additionally, there's sometimes an issue where commits still need to be finalized due to a lack of complete testing or review, leading to many unnecessary and fractured changes, which I am guilty of.
This new contribution guide has a system of pull requests for changes and should help make commits of higher quality.
Note that this will be in combination with other branch rules and changes to repos.
=> feat(contributions): overhaul with PRs for changes

docs/faq-and-troubleshooting/common-questions/roblox-not-opening.md
Terrible formatting on the last one, I can't test anything from here and github codespaces refuse to work.
=> Formatting fixes to Roblox

docs/getting-started/post-installation/software/image-viewer.md, docs/getting-started/post-installation/software/media-playback.md, mkdocs.yml
- add page for recommended image viewers
- update hevc link and icons in media-playback.md
=> feat: page for recommended image viewers

docs/getting-started/post-installation/atlas-folder/security.md
Added a warning for the need of Virtualization for enabling Core Isolation
=> feat: add virtulization warning to core isolation 

docs/getting-started/installation.md, docs/getting-started/post-installation/atlas-folder/interface-tweaks.md
-add section for the toggle extract option in the context menu
-rename restart explorer shortcut -> .cmd
-fix capitalization
=> feat(atlas folder): extract in context menu

docs/getting-started/post-installation/software/media-playback.md
Added MusicBee to the media player page. It's a good foobar2000 alternative for people who want a more "modern" looking UI.
=> feat: add MusicBee

docs/getting-started/post-installation/software/media-playback.md
Adds [Dopamine 2](https://digimezzo.github.io/site/software) to the list of media players.
=> feat(media): add Dopamine 2

docs/getting-started/post-installation/software/media-playback.md, docs/getting-started/post-installation/software/screenshotting.md, docs/getting-started/post-installation/software/text-editors.md
I made all Microsoft store downloads use the Microsoft icon. I also added new apps for screenshotting, text editing, and media playing.
=> Fix inconsistent Microsoft Store icons and add more apps

docs/getting-started/installation.md, docs/install-faq/windows-version-support.md
Hide alternative ISO method until 24h2 support.
Previous PR was closed due to commit verification error.
=> feat(install and FAQ) 24h2 support status

docs/contributing/documentation.md
Removed description error in documentation contribution guidelines
=> Removed description error in contribution guidelines

.github/CODEOWNERS
=> chore: add myself to codeowners

docs/getting-started/installation.md, docs/getting-started/reverting-atlas.md
=> temp: remove msdl (broken)

docs/getting-started/installation.md, docs/getting-started/reverting-atlas.md
github didn't accept my previous commits
=> fix: msdl fixed (2)

docs/getting-started/installation.md
Use new method due to bypassnro disappearing
=> feat: update docs for new local acc method

docs/getting-started/post-installation/drivers/nvidia.md
Deleted that as it has been fixed in the current NVCleanstall version, it now works with no problems.
=> fix: remove outdated info
